### Packages: https://rhel.pkgs.org/9
### Common packages
common_pkgs: 
  - "git-core"
  - "chkconfig"
  - "policycoreutils-python-utils"
  - "libxml2-devel"
  - "libxslt-devel"
  - "libpq-devel"
  - "pcre"
  - "pcre-devel"
  - "git"
  - "gcc"
  - "gcc-c++"
  - "wget"
  - "curl"
  - "patch"
  - "file-libs"
  - "make"
  - "cmake"
  - "automake"
  - "gmp-devel"
  - "systemd"
  - "epel-release"
  - "openssl-devel"
  - "compat-openssl11"
  - "libffi-devel"
  - "libtool"
  - "sudo"
  - "gzip"
  - "unzip"
  - "tar"

### Supervisor
supervisord_bin_path: /usr/bin/supervisord
supervisorctl_bin_path: /usr/bin/supervisorctl
supervisord_conf_file: /etc/supervisord.conf
supervisord_workers_dir : /etc/supervisord.d
supervisord_service: supervisord
supervisor_pkg: supervisor

### Redis
redis_package: redis
redis_daemon: redis
redis_conf_path: /etc/redis.conf
redis_conf_mode: '0644'
redis_enablerepo: epel
redis_version: 6.2.7

### Python
python_pkg: python3
python_bin_path: /usr/bin/python3

### Python packages
python_deps_pkgs:
  - "{{ python_pkg }}-devel"
  - "{{ python_pkg }}-pip"

### Proj
proj_gtest_pkg: gtest-devel
proj_version: proj-9.1.1

### Spatial packages
spatial_deps_pkgs:
  - "geos-devel"
  - "libcurl-devel"
  - "libgeotiff-devel"
  - "libtiff-devel"
  - "sqlite"
  - "sqlite-devel"
  - "{{ proj_gtest_pkg }}"
  - "unzip"

### Java
openjdk_pkg: java-1.8.0-openjdk
java_bin_path: /usr/lib/jvm

### Solr packages
solr_deps_pkgs:
  - "{{ openjdk_pkg }}"
  - "maven"
  - "lsof"
  - "acl"
solr_version: 9.5.0
jts_version: 1.19.0

### PostgreSQL
postgres_version: 15
postgresql_deps_pkgs:
  - "@postgresql:{{ postgres_version }}/server"
  - "postgresql-contrib"
  - postgresql-devel
  - "{{ python_pkg }}-psycopg2"
postgresql_client_pkg: postgresql
postgresql_python3_psycopg: python3-psycopg2

### NGINX packages
nginx_pkg: nginx
nginx_version: 1.22.1

### systemd
systemd_dir: /lib/systemd/system

### service
init_dir: /etc/init.d

## Ansible collections required
ansible_collections:
  - community.general
  - community.postgresql

## uWSGI
uwsgi_version: "2.0.25.1"