- name: Install ckanext-xloader {{ ckanext_versions.ckanext_xloader }}
  vars:
    virtualenv: "{{ ckan_virtualenv }}"
  block:
    - name: Install ckanext-xloader {{ ckanext_versions.ckanext_xloader }}
      become: true
      become_user: "{{ ckan_user }}"
      pip:
        name: git+https://github.com/mjanez/ckanext-xloader.git@{{ ckanext_versions.ckanext_xloader }}#egg=ckanext-xloader
        virtualenv: "{{ ckan_virtualenv }}"
        extra_args: -e
      register: result

    - name: Install ckanext-xloader requirements
      become: true
      become_user: "{{ ckan_user }}"
      pip:
        requirements: "{{ virtualenv }}/src/ckanext-xloader/requirements.txt"
        virtualenv: "{{ virtualenv }}"
      when: result is success

    - name: Install ckanext-xloader requests[security]
      become: true
      become_user: "{{ ckan_user }}"
      pip:
        name: requests[security]
        virtualenv: "{{ virtualenv }}"
        state: latest
      when: result is success
  become: true
  become_user: "{{ ckan_user }}"

- name: Install ckanext-harvest {{ ckanext_versions.ckanext_harvest }}
  vars:
    virtualenv: "{{ ckan_virtualenv }}"
  block:
    - name: Install ckanext-harvest {{ ckanext_versions.ckanext_harvest }}
      become: true
      become_user: "{{ ckan_user }}"
      pip:
        name: git+https://github.com/mjanez/ckanext-harvest.git@{{ ckanext_versions.ckanext_harvest }}#egg=ckanext-harvest
        virtualenv: "{{ ckan_virtualenv }}"
        extra_args: -e
      register: result

    - name: Install ckanext-harvest requirements
      become: true
      become_user: "{{ ckan_user }}"
      pip:
        requirements: "{{ virtualenv }}/src/ckanext-harvest/requirements.txt"
        virtualenv: "{{ virtualenv }}"
      when: result is success
  become: true
  become_user: "{{ ckan_user }}"

- name: Install ckanext-geoview {{ ckanext_versions.ckanext_geoview }}
  vars:
    virtualenv: "{{ ckan_virtualenv }}"
  block:
    - name: Install ckanext-geoview {{ ckanext_versions.ckanext_geoview }}
      become: true
      become_user: "{{ ckan_user }}"
      pip:
        name: git+https://github.com/ckan/ckanext-geoview.git@{{ ckanext_versions.ckanext_geoview }}#egg=ckanext-geoview
        virtualenv: "{{ ckan_virtualenv }}"
        extra_args: -e
      register: result
  become: true
  become_user: "{{ ckan_user }}"

- name: Install ckan/ckanext-spatial {{ ckanext_versions.ckanext_spatial }}
  vars:
    virtualenv: "{{ ckan_virtualenv }}"
  block:
    - name: Install ckan/ckanext-spatial {{ ckanext_versions.ckanext_spatial }}
      become: true
      become_user: "{{ ckan_user }}"
      pip:
        name: git+https://github.com/ckan/ckanext-spatial.git@{{ ckanext_versions.ckanext_spatial }}#egg=ckanext-spatial
        virtualenv: "{{ ckan_virtualenv }}"
        extra_args: -e
      register: result

    - name: Install ckan/ckanext-spatial requirements
      become: true
      become_user: "{{ ckan_user }}"
      pip:
        requirements: "{{ virtualenv }}/src/ckanext-spatial/requirements.txt"
        virtualenv: "{{ virtualenv }}"
      when: result is success
  become: true
  become_user: "{{ ckan_user }}"

- name: Install ckan/ckanext-dcat {{ ckanext_versions.ckanext_dcat }}
  vars:
    virtualenv: "{{ ckan_virtualenv }}"
  block:
    - name: Install ckan/ckanext-dcat {{ ckanext_versions.ckanext_dcat }}
      become: true
      become_user: "{{ ckan_user }}"
      pip:
        name: git+https://github.com/ckan/ckanext-dcat.git@{{ ckanext_versions.ckanext_dcat }}#egg=ckanext-dcat
        virtualenv: "{{ ckan_virtualenv }}"
        extra_args: -e
      register: result

    - name: Install ckan/ckanext-dcat requirements
      become: true
      become_user: "{{ ckan_user }}"
      pip:
        requirements: "{{ virtualenv }}/src/ckanext-dcat/requirements.txt"
        virtualenv: "{{ virtualenv }}"
      when: result is success
  become: true
  become_user: "{{ ckan_user }}"

- name: Install ckanext-scheming {{ ckanext_versions.ckanext_scheming }}
  vars:
    virtualenv: "{{ ckan_virtualenv }}"
  block:
    - name: Install ckanext-scheming {{ ckanext_versions.ckanext_scheming }}
      become: true
      become_user: "{{ ckan_user }}"
      pip:
        name: git+https://github.com/ckan/ckanext-scheming.git@{{ ckanext_versions.ckanext_scheming }}#egg=ckanext-scheming
        virtualenv: "{{ ckan_virtualenv }}"
        extra_args: -e
      register: result
  become: true
  become_user: "{{ ckan_user }}"

- name: Install mjanez/ckanext-resourcedictionary {{ ckanext_versions.ckanext_resourcedictionary }}
  vars:
    virtualenv: "{{ ckan_virtualenv }}"
  block:
    - name: Install mjanez/ckanext-resourcedictionary {{ ckanext_versions.ckanext_resourcedictionary }}
      become: true
      become_user: "{{ ckan_user }}"
      pip:
        name: git+https://github.com/mjanez/ckanext-resourcedictionary.git@{{ ckanext_versions.ckanext_resourcedictionary }}#egg=ckanext-resourcedictionary
        virtualenv: "{{ ckan_virtualenv }}"
        extra_args: -e
      register: result
  become: true
  become_user: "{{ ckan_user }}"

- name: Install ckanext-pages {{ ckanext_versions.ckanext_pages }}
  vars:
    virtualenv: "{{ ckan_virtualenv }}"
  block:
    - name: Install ckanext-pages {{ ckanext_versions.ckanext_pages }}
      become: true
      become_user: "{{ ckan_user }}"
      pip:
        name: git+https://github.com/ckan/ckanext-pages.git@{{ ckanext_versions.ckanext_pages }}#egg=ckanext-pages
        virtualenv: "{{ ckan_virtualenv }}"
        extra_args: -e
      register: result
  become: true
  become_user: "{{ ckan_user }}"

- name: Install ckanext-pdfview {{ ckanext_versions.ckanext_pdfview }}
  vars:
    virtualenv: "{{ ckan_virtualenv }}"
  block:
    - name: Install ckanext-pdfview {{ ckanext_versions.ckanext_pdfview }}
      become: true
      become_user: "{{ ckan_user }}"
      pip:
        name: git+https://github.com/ckan/ckanext-pdfview.git@{{ ckanext_versions.ckanext_pdfview }}#egg=ckanext-pdfview
        virtualenv: "{{ ckan_virtualenv }}"
        extra_args: -e
      register: result
  become: true
  become_user: "{{ ckan_user }}"

- name: Install mjanez/ckanext-fluent {{ ckanext_versions.ckanext_fluent }}
  vars:
    virtualenv: "{{ ckan_virtualenv }}"
  block:
    - name: Install mjanez/ckanext-fluent {{ ckanext_versions.ckanext_fluent }}
      become: true
      become_user: "{{ ckan_user }}"
      pip:
        name: git+https://github.com/mjanez/ckanext-fluent.git@{{ ckanext_versions.ckanext_fluent }}#egg=ckanext-fluent
        virtualenv: "{{ ckan_virtualenv }}"
        extra_args: -e
      register: result
  become: true
  become_user: "{{ ckan_user }}"

- name: Install ckan/ckanext-hierarchy {{ ckanext_versions.ckanext_hierarchy }}
  vars:
    virtualenv: "{{ ckan_virtualenv }}"
  block:
    - name: Install ckan/ckanext-hierarchy {{ ckanext_versions.ckanext_hierarchy }}
      become: true
      become_user: "{{ ckan_user }}"
      pip:
        name: git+https://github.com/ckan/ckanext-hierarchy.git@{{ ckanext_versions.ckanext_hierarchy }}#egg=ckanext-hierarchy
        virtualenv: "{{ ckan_virtualenv }}"
        extra_args: -e
      register: result
  become: true
  become_user: "{{ ckan_user }}"

- name: Installation of custom CKAN extensions for enhancements and theme improvements
  vars:
    virtualenv: "{{ ckan_virtualenv }}"
  block:
    - name: "Install custom extensions"
      become: true
      become_user: "{{ ckan_user }}"
      pip:
        name: git+https://github.com/{{ item.key }}.git@{{ item.value }}#egg={{ item.key.split('/')[-1] }}
        virtualenv: "{{ ckan_virtualenv }}"
        extra_args: -e
      register: result
      loop: "{{ ckanext_custom_plugins | dict2items }}"

    - name: Install requirements
      become: true
      become_user: "{{ ckan_user }}"
      pip:
        requirements: "{{ virtualenv }}/src/{{ item.key.split('/')[-1] }}/requirements.txt"
        virtualenv: "{{ virtualenv }}"
      when: result is success
      loop: "{{ ckanext_custom_plugins | dict2items }}"
  become: true
  become_user: "{{ ckan_user }}"