- name: Check if ckan-pycsw repo exists
  stat:
    path: "{{ pycsw_app_dir }}/.git"
  register: repo

- name: Pull ckan-pycsw:{{ ckan_pycsw_version }} from GitHub
  become: true
  become_user: "{{ ckan_user }}"
  git:
    repo: https://github.com/mjanez/ckan-pycsw
    dest: "{{ pycsw_app_dir }}"
    version: "{{ ckan_pycsw_version }}"
    force: yes

- name: Install PDM
  shell: curl -sSL https://pdm-project.org/install-pdm.py | python3 -
  become: true
  become_user: "{{ ckan_user }}"

- name: Check PDM version
  shell: |
    export PATH=$HOME/.local/bin:$PATH
    pdm --version
  register: pdm_version
  changed_when: false
  become: true
  become_user: "{{ ckan_user }}"

- name: Debug PDM version
  debug:
    var: pdm_version.stdout_lines

- name: Run pdm install --no-self --group prod
  shell: |
    export PATH=$HOME/.local/bin:$PATH
    pdm install --no-self --group prod -v > {{ ckan_tmp_dir }}/ckan-pycsw_pdm_install.log 2>&1
  args:
    chdir: "{{ pycsw_app_dir }}"
  become: true
  become_user: "{{ ckan_user }}"

- name: Run pdm fix to update lock strategy
  shell: |
    export PATH=$HOME/.local/bin:$PATH
    pdm fix
  args:
    chdir: "{{ pycsw_app_dir }}"
  become: true
  become_user: "{{ ckan_user }}"

- name: Remove cite.db if it exists
  file:
    path: "{{ pycsw_app_dir }}/cite.db"
    state: absent
  become: true
  become_user: "{{ ckan_user }}"